apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consul
  template:
    metadata:
    spec:
      containers:
        - image: hashicorp/consul:1.20
          name: badger
          ports:
            - containerPort: 8500
              protocol: TCP
            - containerPort: 8600
              protocol: UDP
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
      restartPolicy: Always
