// Code generated by Kitex v0.9.1. DO NOT EDIT.
package frontendservice

import (
	server "github.com/cloudwego/kitex/server"
	facade "github.com/suyiiyii/hertz101/rpc_gen/kitex_gen/facade"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler facade.FrontendService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler facade.FrontendService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
