{{- range $index, $deployment := .Values.deployments }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deployment.name }}
  labels:
    app: {{ $deployment.name }}
spec:
  replicas: {{ $deployment.replicas }}
  selector:
    matchLabels:
      app: {{ $deployment.name }}
  template:
    metadata:
      labels:
        app: {{ $deployment.name }}
    spec:
      containers:
        - image: {{ $.Values.registry }}/suyiiyii/hertz101-{{ $deployment.name }}:{{ $.Values.tag }}
          name: {{ $deployment.name }}
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "200m"
      restartPolicy: Always
---
{{- end }}